# Adjacency Matrices
#### *Varun Chitturi, Aditya Patel*

#### Project Split:
Varun Chitturi - AdjacencyMatrix Model creation, problems 1-4

Aditya Patel - helper functions, problems 5-8

The purpose of this project is to show how powers of matrices may be used to
investigate graphs. The most commonly depicted graphs in this module consist of airline routes.

Concepts
------

**Graph** - A graph is a set of **Vertices** connected by **Edges**

**Adjacency Matrix** - a way of depicting a graph in the form of a matrix. An adjacency matrix depicting a graph with n vertices will be an $ n\times n $ matrix.
The entry $(n,m)$ in the matrix will be $1$ if vertices $ n $ and $ m $ are connected by an edge, and $0$ if not.

![Figure 1](Assets/Figure1.png)

Figure 1.
$
\begin{bmatrix}
0 & 1 & 0 & 0 & 0 & 0\\
1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 0 & 0 & 1\\
0 & 0 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0 & 1\\
0 & 0 & 1 & 0 & 1 & 1
\end{bmatrix}
$

This matrix has 6 vertices, various edges wherever $(n,m)$ is equal to $1$.

A matrix like this can be used to depict an airline system, with each vertex being an airport and edges being flights between airports.

### Uses of Adjacency Matrices

Adjacency matrices can help us answer questions such as, "How many airports can I go to in two flights?"

In order to connect two airports in two flights, there must be a common layover. We can calculate this using the matrix by seeing which vertices have common edges.

Let's use Figure 1 as an example.

Let $(m,n) = M_{mn}$

$$M_{21}M_{16}+M_{22}M_{26}+M_{23}M_{36}+M_{24}M_{46}+M_{25}M_{56}+M_{26}M_{66}$$ =
$$ 1 \times 0 + 0 \times 0 + 1 \times 1 + 0 \times 0 + 1 \times 1 + 0 \times 1 = 2$$

This allows us to see that there are 2 paths from vertex m to vertex n when we have an intermediate vertex.

From the above equation, it's clear that the number of two-step sequences between vertex $i$ and vertex $j$ in an graph with adjacency matrix M is the $(i,j)$ entry in $M^2$

Similarly, the following is given from the project:
The number of $k$-step sequences between vertex $i$ and vertex $j$ in a graph
with adjacency matrix $M$ is the $(i,j)$ entry in $M^k$.

if M is the adjacency matrix for Figure 1,

$M^2 =
\begin{bmatrix}
1 & 0 & 1 & 0 & 1 & 0\\
0 & 3 & 0 & 0 & 0 & 2\\
1 & 0 & 2 & 0 & 2 & 1\\
0 & 0 & 0 & 0 & 0 & 0\\
1 & 0 & 2 & 0 & 2 & 1\\
0 & 2 & 1 & 0 & 1 & 3
\end{bmatrix}
$

This allows us to easily see the number of 2-step flights from any vertex to any other. Calculating $M^3$ and so on will allow us to see the 3-step and longer paths from vertex to vertex.

If we want to know the least number of flights to go from one airport to another, we can simply calculate $M^2,M^3,M4...$ until the $(m,n)$ has one or more paths.

### Graph Connected
Another commonly asked question is whether it is possible to go from any vertex to any other vertex. We can solve this by calculating $S_k = M^1+M^2+M^3...M^n$, where n is the total number of vertices. This matrix will show the total number of paths from any vertex to any other vertex. There are likely exponentially more paths from one matrix to another in a matrix of n size.


Questions
------
### Question 1
The route map for the northern routes of the now defunct Big Sky Airlines for 2008 is given in Figure 3 below. Produce an adjacency matrix for this map.

![Figure 3](Assets/Figure3.png)

In [21]:
from AdjacencyMatrix import AdjacencyMatrix
import numpy as np

### Question 2
The route map for the northern routes of the now defunct Big Sky Airlines for 2008 is given in Figure 3 below. Produce an adjacency matrix for this map.

In [22]:
flightMatrix = AdjacencyMatrix(matrix=[
[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,1,0,1,0,0,0,0,0,0,0,0,0,0],
[0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],
[0,1,0,0,0,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,1,0,1,0,1,1,1,0,1,1,0],
[0,0,0,0,0,1,0,1,0,0,0,0,0,0,0],
[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],
[0,0,0,0,0,1,0,0,1,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,1,0,0,0],
[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0],
[0,0,0,0,0,1,0,0,0,0,0,1,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,0,0,0,1],
[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
])


### Question 3
For Figure 1, list the three-step sequences between C and F, and confirm that there are indeed 5 of them.

In [23]:
"""
INDEX MAPPING:
A = 0
B = 1
C = 2
D = 3
E = 4
F = 5
"""
figureOneMatrix = AdjacencyMatrix(matrix=[
    [0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 1]
])

print(
    """
    The Three-Step Sequences between C and F are:
    C -> B -> E -> F
    C -> B -> F -> F
    C -> B -> C -> F
    C -> F -> E -> F
    C -> F -> C -> F
    """
)

print(figureOneMatrix.numPaths(2, 5, 3))


    The Three-Step Sequences between C and F are:
    C -> B -> E -> F
    C -> B -> F -> F
    C -> B -> C -> F
    C -> F -> E -> F
    C -> F -> C -> F
    
5


### Question 4
In Figure 1, show that the shortest path between A and F has 3 steps.

In [24]:
print(f"Shortest distance is {figureOneMatrix.shortestDistance(0, 5)}")
print(f"The first matrix with a non zero entry at index 0 and 5 (which map to A and F) is: \n{figureOneMatrix.getStepMatrix(3)}")

Shortest distance is 3
The first matrix with a non zero entry at index 0 and 5 (which map to A and F) is: 
[[0 3 0 0 0 2]
 [3 0 5 0 5 2]
 [0 5 1 0 1 5]
 [0 0 0 0 0 0]
 [0 5 1 0 1 5]
 [2 2 5 0 5 5]]


### Question 4
Which Cape Air cities (Fig. 2) may be reached by a two flight sequence from New Bedford?
Which may be reached by a three flight sequence?



In [25]:
"""
INDEX MAPPING:
Boston = 0
Provincetown = 1
Providence = 2
Hyannis = 3
New Bedford = 4
Martha's Vineyard = 5
Nantucket = 6
"""
index = ["Boston","Provincetown","Providence","Hyannis","New Bedford","Martha's Vineyard","Nantucket"]
figureTwoMatrix = AdjacencyMatrix(matrix=[
    [0, 1, 0, 1, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 1, 1],
    [1, 0, 1, 1, 1, 0, 1],
    [1, 0, 1, 1, 1, 1, 0]
])

print(f"Possible in 2:")
for city in range(0,7):
    if figureTwoMatrix.numPaths(4, city, 2):
        print(f"{city}: {index[city]}")

print(f"Possible in 3:")
for city in range(0,7):
    if figureTwoMatrix.numPaths(4, city, 3):
        print(f"{city}: {index[city]}")

Possible in 2:
0: Boston
2: Providence
3: Hyannis
4: New Bedford
5: Martha's Vineyard
6: Nantucket
Possible in 3:
0: Boston
1: Provincetown
2: Providence
3: Hyannis
4: New Bedford
5: Martha's Vineyard
6: Nantucket


### Question 5
Which trips in the Cape Air network (Fig. 2) take the greatest number of flights?

In [26]:
tripLengths = []
for row in range(0,7):
    rowTrips = []
    for column in range(0,7):
        rowTrips.append(figureTwoMatrix.shortestDistance(row,column))
    tripLengths.append(rowTrips)

longestTrip = 0
for row in tripLengths:
    for column in row:
        if column > longestTrip:
            longestTrip = column

print(f"The following trips have the max length of {longestTrip}.")
for row in range(0,7):
    for column in range(0,7):
        if tripLengths[row][column] == longestTrip:
            print(f"{index[row]} to {index[column]}")

The following trips have the max length of 3.
Provincetown to Providence
Provincetown to New Bedford
Providence to Provincetown
New Bedford to Provincetown


### Question 6
Show that the graph in Figure 1 is not connected by observing Sn.

In [27]:
final = figureOneMatrix.getSN()
print(final)

[[ 17  21  33   0  33  32]
 [ 21  83  53   0  53  98]
 [ 33  53  74   0  74  86]
 [  0   0   0   0   0   0]
 [ 33  53  74   0  74  86]
 [ 32  98  86   0  86 136]]


Because there exist 0 inside the Sn Matrix, the graph is not connected.

### Question 7
Figure 4 shows the May 2001 route map for Spirit Airlines. An updated map may be found at www.spirit.com/RouteMaps.aspx. The adjacency matrix for the map in Figure 4 is the matrix D. The vertices correspond to: Atlantic City, Chicago (O'Hare), Detroit, Fort Lauderdale, Fort Myers, Los Angeles, Melbourne, Myrtle Beach, Newark, New York (LaGuardia), Oakl and, Orlando, Tampa, and Washington (Reagan National). What is the shortest num ber of flights it w ould take to go from Tampa to Newark? How many different ways can you make that trip?


![Figure 4](Assets/Figure4.png)

In [28]:
matrix= [
    [0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,],
    [1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,],
    [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,],
    [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,],
    [1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,],
    [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,],
    [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,]
]
figureFourMatrix = AdjacencyMatrix(matrix=matrix)
vertices = ["Atlantic City","Chicago","Detroit","Fort Lauderdale","Fort Myers","Los Angeles","Melbourne","Myrtle Beach","Newark","New York (LaGuardia)","Oakland","Orlando","Tampa","Washington"]
print(f"Shortest number of flights from Tampa to Newark is {figureFourMatrix.shortestDistance(12,8)}")
print(f"Total number of paths from Tampa to Newark is {figureFourMatrix.getSN()[12][8]}")
print(f"The total number of paths with {figureFourMatrix.shortestDistance(12,8)} paths is {figureFourMatrix.numPaths(12,8,3)}")

Shortest number of flights from Tampa to Newark is 3
Total number of paths from Tampa to Newark is 180310442
The total number of paths with 3 paths is 6


### Question 8
What is the largest number of flights you would need to get from one Spirit city to
another? Which trips take the largest number of flights? How many ways can you
make those trips?

**To solve this, we can create an array of shortest flights and find the largest number of trips from that array.**


In [29]:
shortestFlightsMatrix= []
for row in range(0,figureFourMatrix.n):
    tempRow = []
    for column in range(0,figureFourMatrix.n):
        tempRow.append(figureFourMatrix.shortestDistance(row,column))
    shortestFlightsMatrix.append(tempRow)
longestTrip = 0
countLongest = 0
for row in range(0,figureFourMatrix.n):
    tempRow = []
    for column in range(0,figureFourMatrix.n):
        if longestTrip < shortestFlightsMatrix[row][column]:
            longestTrip = shortestFlightsMatrix[row][column]
            countLongest = 1
        elif longestTrip == shortestFlightsMatrix[row][column]:
            countLongest += 1
print(f"The longest shortest trip possible between two cities is {longestTrip} and this was possible from {countLongest} different trips.")

The longest shortest trip possible between two cities is 3 and this was possible from 32 different trips.


AdjacencyMatrix code
===
This is the Object class we used to help us solve the questions.

In [30]:
class AdjacencyMatrix:
    def __init__(self, matrix=None, n=1):
        """
        Initializes an adjacency matrix with n vertices
        :param n: the number of vertices
        :param matrix: an n x n matrix to make the adjacency matrix
        """
        if matrix is None:
            self.n = n
            self.matrix = np.zeros((n, n))
        else:
            self.matrix = np.array(matrix)
            self.n = self.matrix.shape[0]

    def addEdge(self, v1, v2):
        """
        Adds an edge between v1 and v2
        :param v1: vertex 1
        :param v2: vertex 2
        """
        self.matrix[v1][v2] = 1
        self.matrix[v2][v1] = 1

    def removeEdge(self, v1, v2):
        """
        Removes an edge between v1 and v2
        :param v1: vertex 1
        :param v2: vertex 2
        :return:
        """
        self.matrix[v1][v2] = 0
        self.matrix[v2][v1] = 0

    def __str__(self):
        """
        Prints the adjacency matrix
        """
        return str(self.matrix)

    def getAdjacentVertices(self, v):
        """
        Returns the adjacent vertices of v
        :param v: The vertex to get the adjacent vertices of
        :return: List of adjacent vertices
        """
        adjacentVertices = []
        for i in range(self.n):
            if self.matrix[v][i] == 1:
                adjacentVertices.append(i)
        return adjacentVertices

    def areConnected(self, v1, v2, numSteps=1):
        """
        Returns true if there is a path between v1 and v2 in numVertices steps. numSteps is defaulted to 1.
        :param v1: vertex 1
        :param v2: vertex 2
        :param numSteps: number of steps to get from v1 to v2
        :return: Boolean giving whether there is a path between v1 and v2
        """

        return self.getStepMatrix(numSteps)[v1][v2] != 0

    def shortestDistance(self, v1, v2):
        """
        Returns the shortest distance between v1 and v2
        :param v1: vertex 1
        :param v2: vertex 2
        :return: Shortest number of steps to get from v1 to v2
        """
        if v1 == v2:
            return 0
        for i in range(1, self.n):
            if self.areConnected(v1, v2, i):
                return i
        return -1

    def numPaths(self, v1, v2, numSteps):
        """
        Returns the number of paths from v1 to v2 when going numSteps steps
        :param v1: vertex 1
        :param v2: vertex 2
        :param numSteps: number of steps
        :return: number of paths
        """
        return self.getStepMatrix(numSteps)[v1][v2]

    def getStepMatrix(self, numSteps):
        return np.linalg.matrix_power(self.matrix, numSteps)

    def getSN(self):
        """
        Returns the Sn matrix of the Adjacency Matrix
        """
        final = self.matrix
        for x in range(2, self.n + 1):
            final = np.add(final, np.linalg.matrix_power(self.matrix, x))
        return final